const client=window.supabaseClient||supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);window.supabaseClient=client;
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let years=[],subjects=[],files=[],quizzes=[],services=[],announcements=[],users=[],settings={};
const msg=(t,e=false)=>{$('message').textContent=t||'';$('message').className='admin-msg '+(e?'error':'success')};
function openTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));}
window.openTab=openTab;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$('refreshBtn').onclick=loadAll;
async function boot(){try{const u=await getCurrentUser();if(!u){location.href='login.html?next='+encodeURIComponent(location.href);return}const {data:me,error}=await client.from('profiles').select('role').eq('id',u.id).single();if(error||me?.role!=='admin'){document.body.innerHTML='<main class="section"><div class="container"><div class="card" style="text-align:center"><h2>⛔ غير مصرح بالدخول</h2><p>هذه الصفحة للمديرين فقط.</p><a class="btn primary" href="index.html">العودة للموقع</a></div></div></main>';return}await loadAll()}catch(e){console.error(e);msg('تعذر تحميل لوحة الإدارة. شغّل supabase.sql وتأكد من Supabase.',true)}}
async function loadAll(){msg('جاري التحديث...');const r=await Promise.all([
 client.from('ch_years').select('*').order('sort_order'),client.from('ch_subjects').select('*,ch_years(year_number,title)').order('sort_order'),client.from('ch_materials').select('*,ch_subjects(name)').order('created_at',{ascending:false}),client.from('ch_quizzes').select('*,ch_subjects(name),ch_quiz_questions(id)').order('created_at',{ascending:false}),client.from('ch_services').select('*').order('sort_order'),client.from('ch_announcements').select('*').order('sort_order'),client.from('profiles').select('id,full_name,email,phone,grade,role,created_at').order('created_at',{ascending:false}),client.from('site_settings').select('key,value')]);
for(const x of r){if(x.error){msg(x.error.message,true);return}}[years,subjects,files,quizzes,services,announcements,users]=r.slice(0,7).map(x=>x.data||[]);settings={};(r[7].data||[]).forEach(x=>settings[x.key]=x.value);renderAll();msg('تم التحديث بنجاح.')}
function renderAll(){renderStats();renderYears();fillYearSelect();renderSubjects();fillSubjectSelects();renderFiles();renderQuizzes();renderServices();renderAnnouncements();renderUsers();renderSettings()}
function renderStats(){$('total').textContent=users.length;$('students').textContent=users.filter(x=>x.role!=='admin').length;$('admins').textContent=users.filter(x=>x.role==='admin').length;$('subjectCount').textContent=subjects.length;$('fileCount').textContent=files.length;$('quizCount').textContent=quizzes.length;$('serviceCount').textContent=services.length;$('announcementCount').textContent=announcements.length}
function renderYears(){$('yearsList').innerHTML=years.map(y=>`<div class="item"><div><strong>${esc(y.icon)} ${esc(y.title)}</strong><div class="muted">الفرقة ${y.year_number} • ${esc(y.description||'')} • ${y.active?'ظاهرة':'مخفية'}</div></div><div class="item-actions"><button class="btn small" onclick="editYear('${y.id}')">تعديل</button><button class="danger" onclick="deleteYear('${y.id}')">حذف</button></div></div>`).join('')||'<div class="card">لا توجد فرق.</div>'}
function fillYearSelect(){const o=years.map(y=>`<option value="${y.id}">${esc(y.title)}</option>`).join('');$('subjectYear').innerHTML=o}
window.editYear=id=>{const y=years.find(x=>x.id===id);if(!y)return;$('yearId').value=y.id;$('yearNumber').value=y.year_number;$('yearIcon').value=y.icon||'🎓';$('yearTitle').value=y.title;$('yearDescription').value=y.description||'';$('yearSort').value=y.sort_order;$('yearActive').checked=!!y.active;openTab('years')};
window.deleteYear=async id=>{if(!confirm('حذف الفرقة؟ سيتم حذف موادها وملفاتها واختباراتها المرتبطة.'))return;const r=await client.from('ch_years').delete().eq('id',id);if(r.error)alert(r.error.message);else loadAll()};
$('yearForm').onsubmit=async e=>{e.preventDefault();const id=$('yearId').value,row={year_number:+$('yearNumber').value,title:$('yearTitle').value.trim(),description:$('yearDescription').value.trim(),icon:$('yearIcon').value.trim()||'🎓',sort_order:+$('yearSort').value||0,active:$('yearActive').checked};const r=id?await client.from('ch_years').update(row).eq('id',id):await client.from('ch_years').insert(row);if(r.error)alert(r.error.message);else{$('yearForm').reset();$('yearActive').checked=true;$('yearId').value='';loadAll()}};$('cancelYear').onclick=()=>{$('yearForm').reset();$('yearId').value='';$('yearActive').checked=true};
function renderSubjects(){$('subjectsList').innerHTML=subjects.map(s=>`<div class="item"><div><strong>${esc(s.name)}</strong><div class="muted">${esc(s.ch_years?.title||'')} • ${esc(s.semester)} • ${esc(s.teacher||'без مدرس')} • ${s.active?'ظاهرة':'مخفية'}</div></div><div class="item-actions"><button class="btn small" onclick="editSubject('${s.id}')">تعديل</button><button class="danger" onclick="deleteSubject('${s.id}')">حذف</button></div></div>`).join('')||'<div class="card">لا توجد مواد.</div>'}
window.editSubject=id=>{const s=subjects.find(x=>x.id===id);if(!s)return;$('subjectId').value=id;$('subjectYear').value=s.year_id;$('subjectSemester').value=s.semester;$('subjectName').value=s.name;$('subjectTeacher').value=s.teacher||'';$('subjectGrade').value=s.grade_label||'';$('subjectSort').value=s.sort_order;$('subjectDescription').value=s.description||'';$('subjectActive').checked=!!s.active;openTab('subjects')};
window.deleteSubject=async id=>{if(!confirm('حذف المادة؟'))return;const r=await client.from('ch_subjects').delete().eq('id',id);if(r.error)alert(r.error.message);else loadAll()};
$('subjectForm').onsubmit=async e=>{e.preventDefault();const id=$('subjectId').value,row={year_id:$('subjectYear').value,semester:$('subjectSemester').value,name:$('subjectName').value.trim(),teacher:$('subjectTeacher').value.trim(),grade_label:$('subjectGrade').value.trim()||'—',sort_order:+$('subjectSort').value||0,description:$('subjectDescription').value.trim(),active:$('subjectActive').checked};const r=id?await client.from('ch_subjects').update(row).eq('id',id):await client.from('ch_subjects').insert(row);if(r.error)alert(r.error.message);else{$('subjectForm').reset();$('subjectId').value='';$('subjectActive').checked=true;loadAll()}};$('cancelSubject').onclick=()=>{$('subjectForm').reset();$('subjectId').value='';$('subjectActive').checked=true};
function fillSubjectSelects(){const o=subjects.map(s=>`<option value="${s.id}">${esc(s.name)} — ${esc(s.ch_years?.title||'')}</option>`).join('');$('fileSubject').innerHTML='<option value="">اختر المادة</option>'+o;$('quizSubject').innerHTML='<option value="">اختبار عام</option>'+o}
function renderFiles(){$('filesList').innerHTML=files.map(f=>`<div class="item"><div><strong>${esc(f.title)}</strong><div class="muted">${esc(f.ch_subjects?.name||'')} • ${esc(f.file_name||'')}</div></div><div class="item-actions"><button class="btn small" onclick="previewFile('${f.id}')">فتح</button><button class="danger" onclick="deleteFile('${f.id}','${encodeURIComponent(f.storage_path)}')">حذف</button></div></div>`).join('')||'<div class="card">لا توجد ملفات.</div>'}
$('fileForm').onsubmit=async e=>{e.preventDefault();const sid=$('fileSubject').value,f=$('fileInput').files[0],title=$('fileTitle').value.trim();if(!sid||!f||!title)return;if(f.type!=='application/pdf'){alert('مسموح PDF فقط.');return}if(f.size>50*1024*1024){alert('الحد الأقصى 50MB.');return}const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${sid}/${Date.now()}-${safe}`;$('uploadBtn').disabled=true;$('uploadProgress').textContent='جاري الرفع...';const up=await client.storage.from('chemistryhub-files').upload(path,f,{contentType:'application/pdf',upsert:false});if(up.error){$('uploadBtn').disabled=false;$('uploadProgress').textContent='';alert(up.error.message);return}const ins=await client.from('ch_materials').insert({subject_id:sid,title,file_name:f.name,storage_path:path,mime_type:f.type,size_bytes:f.size});if(ins.error){await client.storage.from('chemistryhub-files').remove([path]);$('uploadBtn').disabled=false;alert(ins.error.message);return}$('uploadBtn').disabled=false;$('fileForm').reset();$('uploadProgress').textContent='تم رفع الملف بنجاح.';loadAll()};
window.previewFile=async id=>{const f=files.find(x=>x.id===id);if(!f)return;const r=await client.storage.from('chemistryhub-files').createSignedUrl(f.storage_path,900);if(r.error)alert(r.error.message);else window.open(r.data.signedUrl,'_blank')};
window.deleteFile=async(id,enc)=>{if(!confirm('حذف الملف نهائياً؟'))return;const path=decodeURIComponent(enc);const r=await client.storage.from('chemistryhub-files').remove([path]);if(r.error){alert(r.error.message);return}const d=await client.from('ch_materials').delete().eq('id',id);if(d.error)alert(d.error.message);else loadAll()};
function addQuestionUI(q={}){const wrap=document.createElement('div');wrap.className='question';wrap.dataset.id=q.id||'';const opts=q.options||['','','',''];wrap.innerHTML=`<button type="button" class="danger" style="float:left" onclick="this.closest('.question').remove()">حذف السؤال</button><label>السؤال</label><textarea class="q-text" rows="2" required>${esc(q.question||'')}</textarea><div class="options"></div>`;const box=wrap.querySelector('.options');opts.slice(0,6).forEach((o,i)=>{const d=document.createElement('div');d.className='option-row';d.innerHTML=`<input class="q-opt" placeholder="اختيار ${i+1}" value="${esc(o)}" required><label class="checkline"><input type="radio" name="correct-${crypto.randomUUID()}" class="q-correct" ${Number(q.correct_index)===i?'checked':''}> صحيح</label>`;box.appendChild(d)});$('questions').appendChild(wrap)}
$('addQuestion').onclick=()=>addQuestionUI();
$('quizForm').onsubmit=async e=>{e.preventDefault();const id=$('quizId').value,payload={title:$('quizTitle').value.trim(),subject_id:$('quizSubject').value||null,description:$('quizDescription').value.trim(),active:$('quizActive').checked};let quizId=id;if(id){const r=await client.from('ch_quizzes').update(payload).eq('id',id);if(r.error){alert(r.error.message);return}}else{const r=await client.from('ch_quizzes').insert(payload).select().single();if(r.error){alert(r.error.message);return}quizId=r.data.id}const d=await client.from('ch_quiz_questions').delete().eq('quiz_id',quizId);if(d.error){alert(d.error.message);return}const rows=[...document.querySelectorAll('#questions .question')].map(q=>{const os=[...q.querySelectorAll('.q-opt')].map(x=>x.value.trim()),ci=[...q.querySelectorAll('.q-correct')].findIndex(x=>x.checked);return{quiz_id:quizId,question:q.querySelector('.q-text').value.trim(),options:os,correct_index:ci<0?0:ci}});if(rows.length){const r=await client.from('ch_quiz_questions').insert(rows);if(r.error){alert(r.error.message);return}}$('quizForm').reset();$('quizId').value='';$('questions').innerHTML='';$('quizActive').checked=true;loadAll()};
window.editQuiz=async id=>{const q=quizzes.find(x=>x.id===id);if(!q)return;const r=await client.from('ch_quiz_questions').select('*').eq('quiz_id',id).order('created_at');if(r.error){alert(r.error.message);return}$('quizId').value=id;$('quizTitle').value=q.title;$('quizSubject').value=q.subject_id||'';$('quizDescription').value=q.description||'';$('quizActive').checked=!!q.active;$('questions').innerHTML='';(r.data||[]).forEach(addQuestionUI);openTab('quizzes')};
window.deleteQuiz=async id=>{if(!confirm('حذف الاختبار؟'))return;const r=await client.from('ch_quizzes').delete().eq('id',id);if(r.error)alert(r.error.message);else loadAll()};
function renderQuizzes(){$('quizzesList').innerHTML=quizzes.map(q=>`<div class="item"><div><strong>${esc(q.title)}</strong><div class="muted">${esc(q.ch_subjects?.name||'اختبار عام')} • ${(q.ch_quiz_questions||[]).length} أسئلة • ${q.active?'متاح':'مخفي'}</div></div><div class="item-actions"><a class="btn small" href="quiz.html?id=${q.id}" target="_blank">فتح</a><button class="btn small" onclick="editQuiz('${q.id}')">تعديل</button><button class="danger" onclick="deleteQuiz('${q.id}')">حذف</button></div></div>`).join('')||'<div class="card">لا توجد اختبارات.</div>'}
function renderServices(){$('servicesList').innerHTML=services.map(s=>`<div class="item"><div><strong>${esc(s.icon)} ${esc(s.title)}</strong><div class="muted">${esc(s.description||'')} • ${s.requires_login?'تحتاج دخول':'عامة'} • ${s.active?'ظاهرة':'مخفية'}</div></div><div class="item-actions"><button class="btn small" onclick="editService('${s.id}')">تعديل</button><button class="danger" onclick="deleteService('${s.id}')">حذف</button></div></div>`).join('')||'<div class="card">لا توجد خدمات.</div>'}
window.editService=id=>{const s=services.find(x=>x.id===id);if(!s)return;$('serviceId').value=id;$('serviceTitle').value=s.title;$('serviceIcon').value=s.icon||'✨';$('serviceDescription').value=s.description||'';$('serviceLink').value=s.link||'#';$('serviceSort').value=s.sort_order;$('serviceLogin').checked=!!s.requires_login;$('serviceActive').checked=!!s.active;openTab('services')};window.deleteService=async id=>{if(!confirm('حذف الخدمة؟'))return;const r=await client.from('ch_services').delete().eq('id',id);if(r.error)alert(r.error.message);else loadAll()};
$('serviceForm').onsubmit=async e=>{e.preventDefault();const id=$('serviceId').value,row={title:$('serviceTitle').value.trim(),icon:$('serviceIcon').value.trim()||'✨',description:$('serviceDescription').value.trim(),link:$('serviceLink').value.trim()||'#',sort_order:+$('serviceSort').value||0,requires_login:$('serviceLogin').checked,active:$('serviceActive').checked};const r=id?await client.from('ch_services').update(row).eq('id',id):await client.from('ch_services').insert(row);if(r.error)alert(r.error.message);else{$('serviceForm').reset();$('serviceId').value='';$('serviceActive').checked=true;loadAll()}};$('cancelService').onclick=()=>{$('serviceForm').reset();$('serviceId').value='';$('serviceActive').checked=true};
function renderAnnouncements(){$('announcementsList').innerHTML=announcements.map(a=>`<div class="item"><div><strong>${esc(a.title)}</strong><div class="muted">${esc(a.body||'')} • ${a.active?'ظاهر':'مخفي'}</div></div><div class="item-actions"><button class="btn small" onclick="editAnnouncement('${a.id}')">تعديل</button><button class="danger" onclick="deleteAnnouncement('${a.id}')">حذف</button></div></div>`).join('')||'<div class="card">لا توجد إعلانات.</div>'}
window.editAnnouncement=id=>{const a=announcements.find(x=>x.id===id);if(!a)return;$('announcementId').value=id;$('announcementTitle').value=a.title;$('announcementBody').value=a.body||'';$('announcementLink').value=a.link||'';$('announcementSort').value=a.sort_order;$('announcementActive').checked=!!a.active;openTab('announcements')};window.deleteAnnouncement=async id=>{if(!confirm('حذف الإعلان؟'))return;const r=await client.from('ch_announcements').delete().eq('id',id);if(r.error)alert(r.error.message);else loadAll()};
$('announcementForm').onsubmit=async e=>{e.preventDefault();const id=$('announcementId').value,row={title:$('announcementTitle').value.trim(),body:$('announcementBody').value.trim(),link:$('announcementLink').value.trim(),sort_order:+$('announcementSort').value||0,active:$('announcementActive').checked};const r=id?await client.from('ch_announcements').update(row).eq('id',id):await client.from('ch_announcements').insert(row);if(r.error)alert(r.error.message);else{$('announcementForm').reset();$('announcementId').value='';$('announcementActive').checked=true;loadAll()}};$('cancelAnnouncement').onclick=()=>{$('announcementForm').reset();$('announcementId').value='';$('announcementActive').checked=true};
function renderUsers(){const t=($('userSearch').value||'').toLowerCase();const rows=users.filter(u=>[u.full_name,u.email,u.phone,u.grade].join(' ').toLowerCase().includes(t));$('usersBody').innerHTML=rows.map(u=>`<tr data-id="${esc(u.id)}"><td>${esc(u.full_name||'—')}</td><td>${esc(u.email||'—')}</td><td>${esc(u.phone||'—')}</td><td>${esc(u.grade||'—')}</td><td><select class="role"><option value="student" ${u.role==='student'?'selected':''}>طالب</option><option value="admin" ${u.role==='admin'?'selected':''}>مدير</option></select></td><td><button class="btn small save-user">حفظ</button></td></tr>`).join('')||'<tr><td colspan="6">لا توجد نتائج.</td></tr>';document.querySelectorAll('.save-user').forEach(b=>b.onclick=async()=>{const row=b.closest('tr'),r=await client.from('profiles').update({role:row.querySelector('.role').value}).eq('id',row.dataset.id);if(r.error)alert(r.error.message);else loadAll()})}$('userSearch').oninput=renderUsers;
function renderSettings(){const s=settings;const set=(id,k,d='')=>$(id).value=s[k]??d;set('setSiteName','site_name','ChemistryHub');set('setBrandSubtitle','brand_subtitle','كلية التربية • قسم الكيمياء');set('setHeroBadge','hero_badge','🎓 بوابتك الدراسية');set('setHeroTitle','hero_title','كلية التربية<br><strong>قسم الكيمياء</strong>');set('setHeroDescription','hero_description');set('setNotice','notice');set('setStatYears','stat_years','4');set('setStatSemesters','stat_semesters','8');set('setStatContent','stat_content','∞');set('setAiUrl','ai_url');set('setAboutBadge','about_badge','About ChemistryHub');set('setAboutTitle','about_title');set('setAboutText','about_text');set('setValue1','about_value_1');set('setValue2','about_value_2');set('setValue3','about_value_3');set('setValue4','about_value_4');set('setFacebook','facebook');set('setYoutube','youtube');set('setWhatsapp','whatsapp');set('setFooterText','footer_text','كلية التربية • قسم الكيمياء')}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const vals={site_name:$('setSiteName').value,brand_subtitle:$('setBrandSubtitle').value,hero_badge:$('setHeroBadge').value,hero_title:$('setHeroTitle').value,hero_description:$('setHeroDescription').value,notice:$('setNotice').value,stat_years:$('setStatYears').value,stat_semesters:$('setStatSemesters').value,stat_content:$('setStatContent').value,ai_url:$('setAiUrl').value,about_badge:$('setAboutBadge').value,about_title:$('setAboutTitle').value,about_text:$('setAboutText').value,about_value_1:$('setValue1').value,about_value_2:$('setValue2').value,about_value_3:$('setValue3').value,about_value_4:$('setValue4').value,facebook:$('setFacebook').value,youtube:$('setYoutube').value,whatsapp:$('setWhatsapp').value,footer_text:$('setFooterText').value};for(const [key,value] of Object.entries(vals)){const r=await client.from('site_settings').upsert({key,value,updated_at:new Date().toISOString()},{onConflict:'key'});if(r.error){alert(r.error.message);return}}Object.assign(settings,vals);msg('تم حفظ إعدادات الموقع.')};
boot();