-- ChemistryHub / EduChem - Complete Supabase setup
-- Run once in Supabase > SQL Editor.
-- Uses the publishable key on the website. NEVER put a Service Role key in frontend files.

-- =========================================================
-- 1) Base tables
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  department text,
  year_level text,
  email text,
  student_code text,
  avatar_url text,
  role text not null default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists department text;
alter table public.profiles add column if not exists year_level text;
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists student_code text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists role text not null default 'student';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text,
  year_level text,
  department text,
  term text,
  teacher text default 'الدكتور',
  code text,
  link text,
  type text default 'mandatory',
  icon text,
  created_at timestamptz not null default now()
);
alter table public.subjects add column if not exists year_level text;
alter table public.subjects add column if not exists department text;
alter table public.subjects add column if not exists term text;
alter table public.subjects add column if not exists name text;
alter table public.subjects add column if not exists teacher text default 'الدكتور';
alter table public.subjects add column if not exists code text;
alter table public.subjects add column if not exists link text;
alter table public.subjects add column if not exists type text default 'mandatory';
alter table public.subjects add column if not exists icon text;
alter table public.subjects add column if not exists created_at timestamptz default now();

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text,
  content text not null,
  image_url text,
  created_at timestamptz not null default now()
);
alter table public.news add column if not exists title text;
alter table public.news add column if not exists content text;
alter table public.news add column if not exists image_url text;
alter table public.news add column if not exists created_at timestamptz default now();

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);
alter table public.notes add column if not exists user_id uuid;
alter table public.notes add column if not exists content text;
alter table public.notes add column if not exists created_at timestamptz default now();

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  year_level text,
  department text,
  time_limit integer not null default 20,
  subject_code text,
  video_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.quizzes add column if not exists title text;
alter table public.quizzes add column if not exists year_level text;
alter table public.quizzes add column if not exists department text;
alter table public.quizzes add column if not exists time_limit integer default 20;
alter table public.quizzes add column if not exists subject_code text;
alter table public.quizzes add column if not exists video_url text;
alter table public.quizzes add column if not exists is_active boolean default true;
alter table public.quizzes add column if not exists created_at timestamptz default now();

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question_text text not null,
  question_type text not null default 'mcq',
  option_1 text,
  option_2 text,
  option_3 text,
  option_4 text,
  correct_option integer,
  explanation text,
  image_url text,
  created_at timestamptz not null default now()
);
alter table public.questions add column if not exists quiz_id bigint;
alter table public.questions add column if not exists question_text text;
alter table public.questions add column if not exists question_type text default 'mcq';
alter table public.questions add column if not exists option_1 text;
alter table public.questions add column if not exists option_2 text;
alter table public.questions add column if not exists option_3 text;
alter table public.questions add column if not exists option_4 text;
alter table public.questions add column if not exists correct_option integer;
alter table public.questions add column if not exists explanation text;
alter table public.questions add column if not exists image_url text;
alter table public.questions add column if not exists created_at timestamptz default now();

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quiz_id bigint references public.quizzes(id) on delete set null,
  student_name text,
  quiz_title text,
  score numeric not null default 0,
  total_score numeric not null default 0,
  created_at timestamptz not null default now()
);
alter table public.quiz_results add column if not exists user_id uuid;
alter table public.quiz_results add column if not exists quiz_id bigint;
alter table public.quiz_results add column if not exists student_name text;
alter table public.quiz_results add column if not exists quiz_title text;
alter table public.quiz_results add column if not exists score numeric default 0;
alter table public.quiz_results add column if not exists total_score numeric default 0;
alter table public.quiz_results add column if not exists created_at timestamptz default now();

-- =========================================================
-- 2) Automatically create/sync a profile after signup
-- =========================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, department, year_level, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'department',
    coalesce(new.raw_user_meta_data->>'year_level', new.raw_user_meta_data->>'department'),
    new.email,
    'student'
  )
  on conflict (id) do update set
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    phone = coalesce(excluded.phone, public.profiles.phone),
    department = coalesce(excluded.department, public.profiles.department),
    year_level = coalesce(excluded.year_level, public.profiles.year_level),
    email = coalesce(excluded.email, public.profiles.email),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- 3) Admin/security functions
-- =========================================================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- SQL Editor / direct administrative operations have no auth.uid()
  -- and must be allowed to set the initial admin role.
  if auth.uid() is null then
    return new;
  end if;

  -- A normal user cannot change their own role.
  if auth.uid() = old.id and not public.is_admin() then
    new.role := old.role;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_prevent_role_escalation on public.profiles;
create trigger trg_prevent_role_escalation
before update on public.profiles
for each row execute function public.prevent_role_escalation();

-- =========================================================
-- 4) RLS
-- =========================================================
alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.news enable row level security;
alter table public.notes enable row level security;
alter table public.quizzes enable row level security;
alter table public.questions enable row level security;
alter table public.quiz_results enable row level security;

-- Profiles
drop policy if exists "profiles_admin_all" on public.profiles;
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (id = auth.uid() or public.is_admin());
create policy "profiles_update_own" on public.profiles for update to authenticated using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy "profiles_admin_all" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Public site content
drop policy if exists "subjects_public_select" on public.subjects;
create policy "subjects_public_select" on public.subjects for select to anon, authenticated using (true);
drop policy if exists "subjects_admin_all" on public.subjects;
create policy "subjects_admin_all" on public.subjects for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "news_public_select" on public.news;
create policy "news_public_select" on public.news for select to anon, authenticated using (true);
drop policy if exists "news_admin_all" on public.news;
create policy "news_admin_all" on public.news for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Notes: student owns their notes; admin can manage all.
drop policy if exists "notes_own_select" on public.notes;
drop policy if exists "notes_own_insert" on public.notes;
drop policy if exists "notes_own_delete" on public.notes;
drop policy if exists "notes_admin_all" on public.notes;
create policy "notes_own_select" on public.notes for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "notes_own_insert" on public.notes for insert to authenticated with check (user_id = auth.uid());
create policy "notes_own_delete" on public.notes for delete to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "notes_admin_all" on public.notes for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Quizzes / questions: active content can be read by logged-in students; admin has full access.
drop policy if exists "quizzes_student_select" on public.quizzes;
drop policy if exists "quizzes_admin_all" on public.quizzes;
create policy "quizzes_student_select" on public.quizzes for select to authenticated using (is_active = true or public.is_admin());
create policy "quizzes_admin_all" on public.quizzes for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "questions_student_select" on public.questions;
drop policy if exists "questions_admin_all" on public.questions;
create policy "questions_student_select" on public.questions for select to authenticated using (exists (select 1 from public.quizzes q where q.id = quiz_id and q.is_active = true) or public.is_admin());
create policy "questions_admin_all" on public.questions for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Results: student can insert/read only own results; admin sees all.
drop policy if exists "quiz_results_student_select" on public.quiz_results;
drop policy if exists "quiz_results_student_insert" on public.quiz_results;
drop policy if exists "quiz_results_admin_all" on public.quiz_results;
create policy "quiz_results_student_select" on public.quiz_results for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "quiz_results_student_insert" on public.quiz_results for insert to authenticated with check (user_id = auth.uid());
create policy "quiz_results_admin_all" on public.quiz_results for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- =========================================================
-- 5) Admin RPCs
-- =========================================================
create or replace function public.admin_list_users()
returns table(
  id uuid,
  email text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  full_name text,
  phone text,
  department text,
  student_code text,
  role text
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  return query
  select u.id, u.email::text, u.created_at, u.last_sign_in_at,
         coalesce(p.full_name, u.raw_user_meta_data->>'full_name')::text,
         p.phone, coalesce(p.year_level, p.department)::text, p.student_code,
         coalesce(p.role,'student')::text
  from auth.users u
  left join public.profiles p on p.id = u.id
  order by u.created_at desc;
end;
$$;
revoke all on function public.admin_list_users() from public;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.admin_delete_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  if p_user_id = auth.uid() then raise exception 'cannot delete current admin'; end if;
  delete from auth.users where id = p_user_id;
end;
$$;
revoke all on function public.admin_delete_user(uuid) from public;
grant execute on function public.admin_delete_user(uuid) to authenticated;

-- =========================================================
-- 6) Avatar storage
-- =========================================================
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "avatar_public_read" on storage.objects;
drop policy if exists "avatar_owner_insert" on storage.objects;
drop policy if exists "avatar_owner_update" on storage.objects;
drop policy if exists "avatar_owner_delete" on storage.objects;
create policy "avatar_public_read" on storage.objects for select using (bucket_id = 'avatars');
create policy "avatar_owner_insert" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "avatar_owner_update" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "avatar_owner_delete" on storage.objects for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- =========================================================
-- 7) Backfill existing auth users into profiles
-- =========================================================
insert into public.profiles (id, full_name, phone, department, year_level, email, role)
select u.id,
       u.raw_user_meta_data->>'full_name',
       u.raw_user_meta_data->>'phone',
       u.raw_user_meta_data->>'department',
       coalesce(u.raw_user_meta_data->>'year_level', u.raw_user_meta_data->>'department'),
       u.email,
       'student'
from auth.users u
on conflict (id) do update set
  email = excluded.email,
  full_name = coalesce(public.profiles.full_name, excluded.full_name),
  phone = coalesce(public.profiles.phone, excluded.phone),
  department = coalesce(public.profiles.department, excluded.department),
  year_level = coalesce(public.profiles.year_level, excluded.year_level),
  updated_at = now();

-- =========================================================
-- 8) After this file succeeds, run ONE separate command to make your account admin:
-- UPDATE public.profiles SET role='admin' WHERE email='YOUR_EMAIL';
-- =========================================================


-- =========================================================
-- 9) Admin bootstrap note
-- =========================================================
-- After running this file, promote your account from SQL Editor:
-- UPDATE public.profiles SET role='admin'
-- WHERE lower(email)=lower('YOUR_EMAIL_HERE');


-- =========================================================
-- 10) Permissions / PostgREST schema refresh
-- =========================================================
-- Make sure the API roles can reach the tables; RLS still controls what
-- authenticated/anonymous users are actually allowed to do.
grant usage on schema public to anon, authenticated;
grant select on public.subjects, public.news to anon, authenticated;
grant select, insert, update, delete on public.subjects, public.news to authenticated;
grant select, insert, update, delete on public.notes, public.quizzes, public.questions, public.quiz_results to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;

-- Identity sequences used by inserts from authenticated clients.
grant usage, select on all sequences in schema public to authenticated;

-- Ask PostgREST/Supabase to refresh its schema cache after this script.
notify pgrst, 'reload schema';
